In [1]:
from sklearn.datasets import load_iris


In [2]:
print("sklearn imported successfully")

sklearn imported successfully


In [5]:
num = int(input("Enter a number: "))
if num >1 :
    for i in range(2, int(num**0.5)+1):
        if num % i==0:
            
            print(f"The number {num} is not prime")
            break
            
        else:
            
            print(f"The number {num} is prime")
            break

else:
    print(f"Number should be greater than 1")

Enter a number:  34


The number 34 is not prime


In [27]:
num = int(input("Enter a number"))
factorial=num
while num != 1:
    #print(factorial)
    
    factorial = factorial * int((num -1))
    #print("First",factorial)
    num-=1
print("Factorial",factorial)
    
    

Enter a number 4


Factorial 24


In [9]:
user_string = str(input("Enter a String"))
reverse_string = ""
for i in user_string:
    reverse_string = i + reverse_string
print(reverse_string)

Enter a String ABCD


DCBA


In [13]:
sentence = str(input("Enter a sentence"))

empty_list = []

for i in sentence:
    empty_list.append(i)
print(len(empty_list))



Enter a sentence Anim Basu


9


In [2]:
import numpy as np

arra1 = np.array([1,2,3,4])

zeroes = np.zeros((3,3))

ones = np.ones((2,4))








In [18]:
zeroes

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [19]:
arra1

array([1, 2, 3, 4])

In [21]:
np_arrange = np.arange(1,100,3)
np_arrange


array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49,
       52, 55, 58, 61, 64, 67, 70, 73, 76, 79, 82, 85, 88, 91, 94, 97])

In [22]:
linspace_array = np.linspace(0,1,5
)
linspace_array

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [9]:
array = np.array([1,2,3,4])
expanded = array[:,np.newaxis]
anotheraxis = expanded[:,np.newaxis]
tarray = anotheraxis.transpose()
tarray

array([[[1, 2, 3, 4]]])

In [12]:
tarray

array([[[1, 2, 3, 4]]])

In [13]:
nparray = np.array([1,2,3,4])
nparray

array([1, 2, 3, 4])

In [19]:
np.random.seed(0)
sales_amount = np.random.randint(20,size=(5,3))
sales_amount

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [3]:
array = np.array([1,2,3,4,5])

In [4]:
array

array([1, 2, 3, 4, 5])

# Introduction to Scikit-Learn (Sklearn)

0. An end to end Sklearn workflow
1. Getting Data Ready
2. Choose the right estimator/ algorithm for our problems
3. Fit the model/algorithm and use it to make predictions on our data
4. Evaluating a model
5. Improve a model
6. Save and load a trained model
7. Putting all together

In [6]:
import pandas as pd
heart_disease = pd.read_csv("data/heart-disease.csv")
heart_disease.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
